name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (semver: patch, minor, major, or exact version e.g., 1.0.5)'
        required: true
        default: 'patch'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: NPM RC
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" >> .npmrc
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.GIT_USER_NAME }}
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}

      - name: Set new package version
        run: |
          npm version ${{ github.event.inputs.version }}

      - name: Push changes and tags
        run: |
          git push origin HEAD:master --tags

      - name: Publish to NPM
        run: npm publish --access public
